import { createHash } from 'node:crypto'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

export const DSH_ROUTES = {
  'anthropic-messages': { adapter: 'deepseek', protocol: 'messages' },
  'openai-chat': { adapter: 'pi-ai', protocol: 'openai-completions' },
  'openai-responses': { adapter: 'pi-ai', protocol: 'openai-responses' },
}

export const PI_AI_KEY_ENV = 'ATRIUM_ROUTE_API_KEY'

export const PI_AI_EFFORTS = [
  ['off', ''],
  ['low', 'low'],
  ['high', 'high'],
  ['max', 'high'],
]

export function dshRoute(apiProtocol) {
  const key = typeof apiProtocol === 'string' ? apiProtocol.trim() : ''
  if (key === '') return DSH_ROUTES['anthropic-messages']
  return DSH_ROUTES[key] ?? null
}

export const generatedPatchDirs = []

export const yamlScalar = value => `'${String(value).replace(/'/g, "''")}'`

export function routeDir() {
  const dir = mkdtempSync(join(tmpdir(), 'atrium-route-'))
  generatedPatchDirs.push(dir)
  return dir
}

export function cleanupPatchDirs() {
  for (const dir of generatedPatchDirs) {
    try {
      rmSync(dir, { recursive: true, force: true })
    } catch { /* the OS temp sweeper is the backstop */ }
  }
}

export function fingerprint(secret) {
  return createHash('sha256').update(String(secret ?? '')).digest('hex').slice(0, 12)
}

export const EXECUTION_MODE_SANDBOX = {
  plan: 'read-only',
  ask: 'workspace-write',
  auto: 'danger-full-access',
}

export function routeKey(request) {
  const route = dshRoute(request.apiProtocol)
  return [
    route === null ? 'unsupported' : `${route.adapter}:${route.protocol}`,
    request.baseUrl ?? 'inherit',
    request.model ?? 'deepseek-flash',
    request.reasoningEffort ?? 'default',
    fingerprint(request.apiKey),
    request.workspace ?? 'inherit',
    request.executionMode ?? 'default',
  ].join('|')
}

export function writeRoutePatch(protocol, baseUrl) {
  const official = baseUrl === undefined || baseUrl.includes('api.deepseek.com')
  if (baseUrl === undefined && official) return null
  const dir = routeDir()
  const path = join(dir, `llm-deepseek.${fingerprint(`${protocol}|${baseUrl ?? ''}`)}.cordis.patch.yml`)
  const lines = [
    '# Generated by @atrium/desktop-host — one route, one runtime.',
    '- id: llm-deepseek',
    '  config:',
  ]
  if (baseUrl !== undefined) lines.push(`    baseURL: ${yamlScalar(baseUrl)}`)
  if (!official) {
    for (const id of ['session-log-deepseek', 'plugin-package-inventory-deepseek']) {
      lines.push(`- id: ${id}`, '  config:', '    enabled: false')
    }
  }
  writeFileSync(path, `${lines.join('\n')}\n`, 'utf8')
  return path
}

export function piAiRouteId(protocol, baseUrl, model) {
  return `atrium-${fingerprint(`${protocol}|${baseUrl ?? ''}|${model ?? ''}`)}`
}

export function writePiAiPatch(routeId, protocol, baseUrl, model, keyEnv) {
  const path = join(routeDir(), 'llm-pi-ai.cordis.patch.yml')
  const lines = [
    '# Generated by @atrium/desktop-host — one route, one runtime.',
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
    `      ${routeId}:`,
    `        api: ${yamlScalar(protocol)}`,
    `        apiKeyEnv: ${yamlScalar(keyEnv)}`,
  ]
  if (baseUrl !== undefined) lines.push(`        baseURL: ${yamlScalar(baseUrl)}`)
  lines.push('        models:', `          - id: ${yamlScalar(model ?? '')}`, '            reasoningEfforts:')
  for (const [level, wire] of PI_AI_EFFORTS) {
    lines.push(wire === '' ? `              ${level}:` : `              ${level}: ${wire}`)
  }
  writeFileSync(path, `${lines.join('\n')}\n`, 'utf8')
  return path
}
